"""Initial schema for audit_logs and purchase_requisitions

Revision ID: 8e4eab8095e1
Revises: 
Create Date: 2026-08-10 22:52:32.373035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e4eab8095e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_thread_id'), 'audit_logs', ['thread_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('purchase_requisitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pr_number', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('structured_requirement', sa.JSON(), nullable=True),
    sa.Column('demand_analysis', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_requisitions_pr_number'), 'purchase_requisitions', ['pr_number'], unique=True)
    op.create_index(op.f('ix_purchase_requisitions_user_id'), 'purchase_requisitions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_requisitions_user_id'), table_name='purchase_requisitions')
    op.drop_index(op.f('ix_purchase_requisitions_pr_number'), table_name='purchase_requisitions')
    op.drop_table('purchase_requisitions')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_thread_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
